### ISSUE TITLE
Allow for adding a stylesheet to sitemap or sitemap index

### ISSUE THREAD

**Issue by andersme** [marthijn/Sidio.Sitemap.Core#17]
Sometimes it's nice to have a stylesheet for a sitemap, so that when you're looking at it in the browser, it's easier to navigate. I would love to be able add something like this: [https://www.sitemap.style/](https://www.sitemap.style/)

**Comment by marthijn** [comment]
Hi Mike,
Thanks for your suggestion. I will look into it in the coming weeks. Also, feel free to make a PR if you need this on short notice :)

**Comment by marthijn** [comment]
A preview version with this feature is available via NuGet: https://www.nuget.org/packages/Sidio.Sitemap.Core/2.6.0-preview
Usage: `var sitemap = new Sitemap("my-stylesheet.xslt");`
Let me know what you think!

**Comment by marthijn** [comment]
This feature is released in version 2.6.1
